// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA724-0WeX8nol0Ib0A0CLWKHwEKSYUaZ8',
    appId: '1:540639980844:web:7e0981aba9c1f092d39089',
    messagingSenderId: '540639980844',
    projectId: 'form-builder-yuvraj',
    authDomain: 'form-builder-yuvraj.firebaseapp.com',
    storageBucket: 'form-builder-yuvraj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQj1ptIQLAj7KMv-R2cOaY_T7Nmj-qWqo',
    appId: '1:540639980844:android:c5da5ca88c4be8b5d39089',
    messagingSenderId: '540639980844',
    projectId: 'form-builder-yuvraj',
    storageBucket: 'form-builder-yuvraj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnMvzwX_r9JyngF4tUe84cvnpcQkevCDQ',
    appId: '1:540639980844:ios:057628854ba89770d39089',
    messagingSenderId: '540639980844',
    projectId: 'form-builder-yuvraj',
    storageBucket: 'form-builder-yuvraj.firebasestorage.app',
    iosBundleId: 'com.example.formBuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnMvzwX_r9JyngF4tUe84cvnpcQkevCDQ',
    appId: '1:540639980844:ios:057628854ba89770d39089',
    messagingSenderId: '540639980844',
    projectId: 'form-builder-yuvraj',
    storageBucket: 'form-builder-yuvraj.firebasestorage.app',
    iosBundleId: 'com.example.formBuilderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA724-0WeX8nol0Ib0A0CLWKHwEKSYUaZ8',
    appId: '1:540639980844:web:ea027c66c4e7f07ad39089',
    messagingSenderId: '540639980844',
    projectId: 'form-builder-yuvraj',
    authDomain: 'form-builder-yuvraj.firebaseapp.com',
    storageBucket: 'form-builder-yuvraj.firebasestorage.app',
  );
}
